"""Remove durum from KontrolRaporu

Revision ID: 20c11a7f0223
Revises: 
Create Date: 2025-02-05 20:22:21.691014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c11a7f0223'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kontrol_raporu', schema=None) as batch_op:
        batch_op.drop_column('durum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kontrol_raporu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('durum', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
