"""empty message

Revision ID: 8880b54e436e
Revises: 20c11a7f0223
Create Date: 2025-02-07 22:24:11.802163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8880b54e436e'
down_revision = '20c11a7f0223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dosya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_adi', sa.String(length=200), nullable=False),
    sa.Column('vergi_no', sa.String(length=10), nullable=False),
    sa.Column('donem', sa.String(length=7), nullable=False),
    sa.Column('iade_turu', sa.String(length=50), nullable=False),
    sa.Column('iade_tutari', sa.Float(), nullable=False),
    sa.Column('durum', sa.String(length=50), nullable=False),
    sa.Column('acilis_tarihi', sa.DateTime(), nullable=False),
    sa.Column('son_islem_tarihi', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('arsivde', sa.Boolean(), nullable=True),
    sa.Column('kayit_tarihi', sa.DateTime(), nullable=True),
    sa.Column('karsit_liste_tarihi', sa.DateTime(), nullable=True),
    sa.Column('rapor_teslim_tarihi', sa.DateTime(), nullable=True),
    sa.Column('iade_talep_tarihi', sa.DateTime(), nullable=True),
    sa.Column('rapor_ekleri_tarihi', sa.DateTime(), nullable=True),
    sa.Column('makbuz_tarihi', sa.DateTime(), nullable=True),
    sa.Column('makbuz_no', sa.String(length=50), nullable=True),
    sa.Column('iade_listesi_onay', sa.Boolean(), nullable=True),
    sa.Column('rapor_onay', sa.Boolean(), nullable=True),
    sa.Column('teminat_mektubu', sa.Boolean(), nullable=True),
    sa.Column('on_kontrol_talebi', sa.Boolean(), nullable=True),
    sa.Column('iade_sekli', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dosya_hareket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dosya_id', sa.Integer(), nullable=False),
    sa.Column('islem_tarihi', sa.DateTime(), nullable=False),
    sa.Column('islem', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dosya_id'], ['dosya.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eksiklik_yazisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dosya_id', sa.Integer(), nullable=False),
    sa.Column('dosya_adi', sa.String(length=255), nullable=False),
    sa.Column('yuklenme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('cevaplandirma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dosya_id'], ['dosya.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('karsit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dosya_id', sa.Integer(), nullable=False),
    sa.Column('kayit_acilis_tarihi', sa.DateTime(), nullable=False),
    sa.Column('alt_firma_sirasi', sa.Integer(), nullable=False),
    sa.Column('alt_firma_unvani', sa.String(length=200), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('ilgili_kisi', sa.String(length=100), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('karsit_durumu', sa.String(length=20), nullable=False),
    sa.Column('sonraki_karsit_dikkat', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dosya_id'], ['dosya.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kontrol_raporu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dosya_id', sa.Integer(), nullable=False),
    sa.Column('dosya_adi', sa.String(length=255), nullable=False),
    sa.Column('yuklenme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dosya_id'], ['dosya.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kontrol_raporu')
    op.drop_table('karsit')
    op.drop_table('eksiklik_yazisi')
    op.drop_table('dosya_hareket')
    op.drop_table('dosya')
    op.drop_table('user')
    # ### end Alembic commands ###
